//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisBuddy.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BisBuddy.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark all as not Collected.
        /// </summary>
        internal static string AllCollectedTooltip {
            get {
                return ResourceManager.GetString("AllCollectedTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock all as Collected.
        /// </summary>
        internal static string AllUncollectedTooltip {
            get {
                return ResourceManager.GetString("AllUncollectedTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark as not Collected.
        /// </summary>
        internal static string AutomaticallyCollectedTooltip {
            get {
                return ResourceManager.GetString("AutomaticallyCollectedTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bright List Items.
        /// </summary>
        internal static string BrightListItemHighlightingCheckbox {
            get {
                return ResourceManager.GetString("BrightListItemHighlightingCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locks list item highlight opacity to max to increase contrast. Disabling may fix issues with some custom UIs.
        /// </summary>
        internal static string BrightListItemHighlightingHelp {
            get {
                return ResourceManager.GetString("BrightListItemHighlightingHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Settings.
        /// </summary>
        internal static string ConfigGeneralSectionHeader {
            get {
                return ResourceManager.GetString("ConfigGeneralSectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window Highlighting.
        /// </summary>
        internal static string ConfigHighlightingSectionHeader {
            get {
                return ResourceManager.GetString("ConfigHighlightingSectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Updates.
        /// </summary>
        internal static string ConfigInventorySectionHeader {
            get {
                return ResourceManager.GetString("ConfigInventorySectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Config.
        /// </summary>
        internal static string ConfigWindowTitle {
            get {
                return ResourceManager.GetString("ConfigWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, Delete.
        /// </summary>
        internal static string DeleteGearsetConfirmButton {
            get {
                return ResourceManager.GetString("DeleteGearsetConfirmButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This cannot be undone!.
        /// </summary>
        internal static string DeleteGearsetConfirmTooltip {
            get {
                return ResourceManager.GetString("DeleteGearsetConfirmTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Gearset?.
        /// </summary>
        internal static string DeleteGearsetPopupTitle {
            get {
                return ResourceManager.GetString("DeleteGearsetPopupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this Gearset. Shift+Click to quick delete.
        /// </summary>
        internal static string DeleteGearsetTooltip {
            get {
                return ResourceManager.GetString("DeleteGearsetTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this Gearset. Click to quick delete.
        /// </summary>
        internal static string DeleteGearsetTooltipQuick {
            get {
                return ResourceManager.GetString("DeleteGearsetTooltipQuick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Gearset.
        /// </summary>
        internal static string DisabledGearsetTooltip {
            get {
                return ResourceManager.GetString("DisabledGearsetTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Gearset.
        /// </summary>
        internal static string EnabledGearsetTooltip {
            get {
                return ResourceManager.GetString("EnabledGearsetTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Default Color.
        /// </summary>
        internal static string GearsetDefaultColorCheckbox {
            get {
                return ResourceManager.GetString("GearsetDefaultColorCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether to use the default highlight color (as set in configuration),
        ///or to have a unique color to highlight items in.
        /// </summary>
        internal static string GearsetDefaultColorTooltip {
            get {
                return ResourceManager.GetString("GearsetDefaultColorTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color needed items for this gearset are highlighted in.
        /// </summary>
        internal static string GearsetHighlightColorButtonTooltip {
            get {
                return ResourceManager.GetString("GearsetHighlightColorButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gearset Highlight Color.
        /// </summary>
        internal static string GearsetHighlightColorLabel {
            get {
                return ResourceManager.GetString("GearsetHighlightColorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON.
        /// </summary>
        internal static string GearsetJsonButton {
            get {
                return ResourceManager.GetString("GearsetJsonButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy gearset JSON to clipboard.
        /// </summary>
        internal static string GearsetJsonTooltip {
            get {
                return ResourceManager.GetString("GearsetJsonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string GearsetStringButton {
            get {
                return ResourceManager.GetString("GearsetStringButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy {0} text to clipboard.
        /// </summary>
        internal static string GearsetStringTooltip {
            get {
                return ResourceManager.GetString("GearsetStringTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        internal static string GearsetUrlButton {
            get {
                return ResourceManager.GetString("GearsetUrlButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy {0} link to clipboard.
        /// </summary>
        internal static string GearsetUrlTooltip {
            get {
                return ResourceManager.GetString("GearsetUrlTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight Appearance.
        /// </summary>
        internal static string GeneralConfigurationHighlightAppearanceCategory {
            get {
                return ResourceManager.GetString("GeneralConfigurationHighlightAppearanceCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miscellaneous.
        /// </summary>
        internal static string GeneralConfigurationMiscellaneousCategory {
            get {
                return ResourceManager.GetString("GeneralConfigurationMiscellaneousCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collected Only.
        /// </summary>
        internal static string HighlightCollectedItemMateriaCheckbox {
            get {
                return ResourceManager.GetString("HighlightCollectedItemMateriaCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Highlight Color.
        /// </summary>
        internal static string HighlightColorButtonLabel {
            get {
                return ResourceManager.GetString("HighlightColorButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color needed items are highlighted in by default or with color conflicts.
        /// </summary>
        internal static string HighlightColorButtonTooltip {
            get {
                return ResourceManager.GetString("HighlightColorButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What color to highlight needed items in by default, or if an item is needed by gearsets different colors
        ///
        ///Use alpha channel to adjust highlight intensity on items/icons
        ///List menu highlights are not affected.
        /// </summary>
        internal static string HighlightColorHelp {
            get {
                return ResourceManager.GetString("HighlightColorHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventories.
        /// </summary>
        internal static string HighlightInventoriesCheckbox {
            get {
                return ResourceManager.GetString("HighlightInventoriesCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlights items needed for gearsets in inventories (inventory, retainer, saddlebag).
        /// </summary>
        internal static string HighlightInventoriesHelp {
            get {
                return ResourceManager.GetString("HighlightInventoriesHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Tooltips.
        /// </summary>
        internal static string HighlightItemTooltipsCheckbox {
            get {
                return ResourceManager.GetString("HighlightItemTooltipsCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lists what gearsets need the item being hovered over in the item tooltip.
        /// </summary>
        internal static string HighlightItemTooltipsHelp {
            get {
                return ResourceManager.GetString("HighlightItemTooltipsHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketboard.
        /// </summary>
        internal static string HighlightMarketboardCheckbox {
            get {
                return ResourceManager.GetString("HighlightMarketboardCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlights items needed for gearsets on the marketboard.
        /// </summary>
        internal static string HighlightMarketboardHelp {
            get {
                return ResourceManager.GetString("HighlightMarketboardHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Materia Melding.
        /// </summary>
        internal static string HighlightMateriaMeldingCheckbox {
            get {
                return ResourceManager.GetString("HighlightMateriaMeldingCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlights gearpieces needing melds and the materia needed for those gearpieces in melding windows.
        /// </summary>
        internal static string HighlightMateriaMeldingHelp {
            get {
                return ResourceManager.GetString("HighlightMateriaMeldingHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need/Greed Windows.
        /// </summary>
        internal static string HighlightNeedGreedCheckbox {
            get {
                return ResourceManager.GetString("HighlightNeedGreedCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlights items needed for gearsets in Need/Greed loot windows.
        /// </summary>
        internal static string HighlightNeedGreedHelp {
            get {
                return ResourceManager.GetString("HighlightNeedGreedHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Materia Only.
        /// </summary>
        internal static string HighlightNextMateriaCheckbox {
            get {
                return ResourceManager.GetString("HighlightNextMateriaCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether to only highlight the next materia, or to highlight all available materia to meld. Useful for advanced melding
        ///Note: Ensure no erroneous materia is already melded for most accurate highlighting
        ///
        ///When ON: Only the next materia a gearpiece needs to meld is highlighted
        ///When OFF: All materia a gearpiece needs is highlighted in the melding window
        ///
        ///Example
        ///Gearpiece needs the following melds: [+36 CRT, +36 DET]
        ///
        ///When ON: +36 CRT is highlighted
        ///When OFF: +36 CRT and +36 DET are highlighted.
        /// </summary>
        internal static string HighlightNextMateriaHelp {
            get {
                return ResourceManager.GetString("HighlightNextMateriaHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meld Prerequisites.
        /// </summary>
        internal static string HighlightPrerequisiteMateriaCheckbox {
            get {
                return ResourceManager.GetString("HighlightPrerequisiteMateriaCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether prerequisites should be considered meld targets for the materia listed for gearpieces they are a prerequisite for
        ///
        ///When ON: Prerequisites will be highlighted when melding materia, requiring the materia the final gearpiece needs.
        ///The gearpiece in the menu will reflect the melds of the prerequisite while it is not yet obtained.
        ///When OFF: Only the main gearpiece will be highlighted when melding materia.
        ///
        ///Example
        ///Gearpiece (unobtained): Augmented Historia Ring of Casting [+54 DET, +54 CRT]
        ///Prere [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HighlightPrerequisiteMateriaHelp {
            get {
                return ResourceManager.GetString("HighlightPrerequisiteMateriaHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shops/Exchanges.
        /// </summary>
        internal static string HighlightShopExchangesCheckbox {
            get {
                return ResourceManager.GetString("HighlightShopExchangesCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlights items needed for gearsets in NPC shops/item exchanges.
        /// </summary>
        internal static string HighlightShopExchangesHelp {
            get {
                return ResourceManager.GetString("HighlightShopExchangesHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncollected Item Materia.
        /// </summary>
        internal static string HighlightUncollectedItemMateriaCheckbox {
            get {
                return ResourceManager.GetString("HighlightUncollectedItemMateriaCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether materia needed for gearpieces that are not yet collected should be highlighted.
        ///
        ///When ON: Materia needed for gearpieces will be highlighted regardless of collected status
        ///When OFF: If a gearpiece isn&apos;t collected, its materia will not be highlighted anywhere.
        /// </summary>
        internal static string HighlightUncollectedItemMateriaHelp {
            get {
                return ResourceManager.GetString("HighlightUncollectedItemMateriaHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gearset sheet link from Etro.gg
        ///ex: https://etro.gg/gearset/4b5f4ed3-4832-4fd5-b134-3429ea8caf37.
        /// </summary>
        internal static string ImportEtroTooltip {
            get {
                return ResourceManager.GetString("ImportEtroTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Fail:.
        /// </summary>
        internal static string ImportFailBase {
            get {
                return ResourceManager.GetString("ImportFailBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Internal error.
        /// </summary>
        internal static string ImportFailInternalError {
            get {
                return ResourceManager.GetString("ImportFailInternalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Invalid input for {1}.
        /// </summary>
        internal static string ImportFailInvalidInput {
            get {
                return ResourceManager.GetString("ImportFailInvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Invalid response received.
        /// </summary>
        internal static string ImportFailInvalidResponse {
            get {
                return ResourceManager.GetString("ImportFailInvalidResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} No gearsets found/imported.
        /// </summary>
        internal static string ImportFailNoGearsets {
            get {
                return ResourceManager.GetString("ImportFailNoGearsets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Import would exceed gearset limit.
        /// </summary>
        internal static string ImportFailTooManyGearsets {
            get {
                return ResourceManager.GetString("ImportFailTooManyGearsets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import from {0}.
        /// </summary>
        internal static string ImportGearsetButton {
            get {
                return ResourceManager.GetString("ImportGearsetButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string ImportGearsetLoading {
            get {
                return ResourceManager.GetString("ImportGearsetLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import a new gearset from {0}.
        /// </summary>
        internal static string ImportGearsetTooltip {
            get {
                return ResourceManager.GetString("ImportGearsetTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid URL.
        /// </summary>
        internal static string ImportInvalidUrl {
            get {
                return ResourceManager.GetString("ImportInvalidUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gearset JSON exported from existing plugin gearset
        ///ex: {&quot;Id&quot;:&quot;50399235-5794-4ccb-906f-ddd9....
        /// </summary>
        internal static string ImportJsonTooltip {
            get {
                return ResourceManager.GetString("ImportJsonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Gearsets Found.
        /// </summary>
        internal static string ImportNoGearsets {
            get {
                return ResourceManager.GetString("ImportNoGearsets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Success: {2} gearset(s) imported.
        /// </summary>
        internal static string ImportSuccess {
            get {
                return ResourceManager.GetString("ImportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plaintext gearset exported from Teamcraft
        ///ex:
        ///**Everseeker&apos;s Pickaxe HQ**
        ///        
        ///- Gatherer&apos;s Guile Materia X
        ///
        ///**Everseeker&apos;s Coat of Gath....
        /// </summary>
        internal static string ImportTeamcraftTooltip {
            get {
                return ResourceManager.GetString("ImportTeamcraftTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Gearset.
        /// </summary>
        internal static string ImportWindowTitle {
            get {
                return ResourceManager.GetString("ImportWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gearset sheet link exported from Xivgear.app
        ///ex: https://xivgear.app/?page=sl%%7C9ee61d69-7daa-41bd-9c28-8a0f0055f90f.
        /// </summary>
        internal static string ImportXivgearTooltip {
            get {
                return ResourceManager.GetString("ImportXivgearTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string InventoryScanLoading {
            get {
                return ResourceManager.GetString("InventoryScanLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} gearpieces updated.
        /// </summary>
        internal static string InventoryScanUpdated {
            get {
                return ResourceManager.GetString("InventoryScanUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please log in to view/add gearsets.
        /// </summary>
        internal static string LoggedOutText {
            get {
                return ResourceManager.GetString("LoggedOutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection status locked. Inventory syncs will not uncollect.
        /// </summary>
        internal static string ManuallyCollectedTooltip {
            get {
                return ResourceManager.GetString("ManuallyCollectedTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left click to {0} {1}
        ///Right click to search for in inventory.
        /// </summary>
        internal static string MateriaTooltip {
            get {
                return ResourceManager.GetString("MateriaTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meld.
        /// </summary>
        internal static string MeldVerb {
            get {
                return ResourceManager.GetString("MeldVerb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Materia Melds.
        /// </summary>
        internal static string MeldWindowHeader {
            get {
                return ResourceManager.GetString("MeldWindowHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Gearset.
        /// </summary>
        internal static string NewGearsetButton {
            get {
                return ResourceManager.GetString("NewGearsetButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import a new gearset.
        /// </summary>
        internal static string NewGearsetTooltip {
            get {
                return ResourceManager.GetString("NewGearsetTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum of {0} gearsets.
        /// </summary>
        internal static string NewGearsetTooltipMaxGearsets {
            get {
                return ResourceManager.GetString("NewGearsetTooltipMaxGearsets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No gearsets found. Add one or more gearsets to get started.
        /// </summary>
        internal static string NoGearsetsText {
            get {
                return ResourceManager.GetString("NoGearsetsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open config.
        /// </summary>
        internal static string OpenConfigTooltip {
            get {
                return ResourceManager.GetString("OpenConfigTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left click to {0}
        ///Right click to search for in inventory.
        /// </summary>
        internal static string PrerequisiteTooltipBase {
            get {
                return ResourceManager.GetString("PrerequisiteTooltipBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename Gearset.
        /// </summary>
        internal static string RenameGearsetTooltip {
            get {
                return ResourceManager.GetString("RenameGearsetTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search inventory for {0}.
        /// </summary>
        internal static string SearchInventoryForItemTooltip {
            get {
                return ResourceManager.GetString("SearchInventoryForItemTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strict Materia Matching.
        /// </summary>
        internal static string StrictMateriaMatchingCheckbox {
            get {
                return ResourceManager.GetString("StrictMateriaMatchingCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether auto assignment treats gearpieces with different materia as unique items
        ///
        ///When ON: Each gearpiece entry is considered unique based on its materia. So if you have multiple entries for the same gearpiece with different materia, a single inventory item can only satisfy one of them
        ///When OFF: Auto assignment ignores the materia differences and only looks at the actual gearpiece. One inventory item can satisfy multiple entries for the same gearpiece even if their materia differ
        ///
        ///Example
        ///Inventory: 1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StrictMateriaMatchingHelp {
            get {
                return ResourceManager.GetString("StrictMateriaMatchingHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync Inventory.
        /// </summary>
        internal static string SyncInventoryButton {
            get {
                return ResourceManager.GetString("SyncInventoryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update gearsets with items from your inventory.
        /// </summary>
        internal static string SyncInventoryTooltip {
            get {
                return ResourceManager.GetString("SyncInventoryTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock as Collected.
        /// </summary>
        internal static string UncollectedTooltip {
            get {
                return ResourceManager.GetString("UncollectedTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unmeld.
        /// </summary>
        internal static string UnmeldVerb {
            get {
                return ResourceManager.GetString("UnmeldVerb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Changes.
        /// </summary>
        internal static string UpdateOnItemChangeCheckbox {
            get {
                return ResourceManager.GetString("UpdateOnItemChangeCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When a change is detected in character inventories, update gearsets with items in inventories (inventory, armoury chest, equipped).
        /// </summary>
        internal static string UpdateOnItemChangeHelp {
            get {
                return ResourceManager.GetString("UpdateOnItemChangeHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login/Load.
        /// </summary>
        internal static string UpdateOnLoginLoadCheckbox {
            get {
                return ResourceManager.GetString("UpdateOnLoginLoadCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When logging in or loading {0}, update gearsets with items in inventories (inventory, armoury chest, equipped).
        /// </summary>
        internal static string UpdateOnLoginLoadHelp {
            get {
                return ResourceManager.GetString("UpdateOnLoginLoadHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin Changes.
        /// </summary>
        internal static string UpdateOnPluginChangesCheckbox {
            get {
                return ResourceManager.GetString("UpdateOnPluginChangesCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When updating {0} gearsets or settings, update gearsets with items in inventories (inventory, armoury chest, equipped).
        /// </summary>
        internal static string UpdateOnPluginChangesHelp {
            get {
                return ResourceManager.GetString("UpdateOnPluginChangesHelp", resourceCulture);
            }
        }
    }
}
