//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisBuddy.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BisBuddy.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark all as not Collected.
        /// </summary>
        internal static string AllCollectedTooltip {
            get {
                return ResourceManager.GetString("AllCollectedTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock all as Collected.
        /// </summary>
        internal static string AllUncollectedTooltip {
            get {
                return ResourceManager.GetString("AllUncollectedTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark as not Collected.
        /// </summary>
        internal static string AutomaticallyCollectedTooltip {
            get {
                return ResourceManager.GetString("AutomaticallyCollectedTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Highlighting.
        /// </summary>
        internal static string ConfigHighlightingSectionHeader {
            get {
                return ResourceManager.GetString("ConfigHighlightingSectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Updates.
        /// </summary>
        internal static string ConfigInventorySectionHeader {
            get {
                return ResourceManager.GetString("ConfigInventorySectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Config.
        /// </summary>
        internal static string ConfigWindowTitle {
            get {
                return ResourceManager.GetString("ConfigWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, Delete.
        /// </summary>
        internal static string DeleteGearsetConfirmButton {
            get {
                return ResourceManager.GetString("DeleteGearsetConfirmButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This cannot be undone!.
        /// </summary>
        internal static string DeleteGearsetConfirmTooltip {
            get {
                return ResourceManager.GetString("DeleteGearsetConfirmTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Gearset?.
        /// </summary>
        internal static string DeleteGearsetPopupTitle {
            get {
                return ResourceManager.GetString("DeleteGearsetPopupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this Gearset. Shift+Click to quick delete.
        /// </summary>
        internal static string DeleteGearsetTooltip {
            get {
                return ResourceManager.GetString("DeleteGearsetTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this Gearset. Click to quick delete.
        /// </summary>
        internal static string DeleteGearsetTooltipQuick {
            get {
                return ResourceManager.GetString("DeleteGearsetTooltipQuick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Gearset.
        /// </summary>
        internal static string DisabledGearsetTooltip {
            get {
                return ResourceManager.GetString("DisabledGearsetTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Gearset.
        /// </summary>
        internal static string EnabledGearsetTooltip {
            get {
                return ResourceManager.GetString("EnabledGearsetTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON.
        /// </summary>
        internal static string GearsetJsonButton {
            get {
                return ResourceManager.GetString("GearsetJsonButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy gearset JSON to clipboard.
        /// </summary>
        internal static string GearsetJsonTooltip {
            get {
                return ResourceManager.GetString("GearsetJsonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        internal static string GearsetUrlButton {
            get {
                return ResourceManager.GetString("GearsetUrlButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy {0} link to clipboard.
        /// </summary>
        internal static string GearsetUrlTooltip {
            get {
                return ResourceManager.GetString("GearsetUrlTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight Color.
        /// </summary>
        internal static string HighlightColorButtonLabel {
            get {
                return ResourceManager.GetString("HighlightColorButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color needed items are highlighted in.
        /// </summary>
        internal static string HighlightColorButtonTooltip {
            get {
                return ResourceManager.GetString("HighlightColorButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What color to highlight needed items in
        ///
        ///Use alpha channel to adjust highlight intensity on items/icons
        ///List menu highlights are not affected.
        /// </summary>
        internal static string HighlightColorHelp {
            get {
                return ResourceManager.GetString("HighlightColorHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventories.
        /// </summary>
        internal static string HighlightInventoriesCheckbox {
            get {
                return ResourceManager.GetString("HighlightInventoriesCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlights items needed for gearsets in inventories (inventory, retainer, saddlebag).
        /// </summary>
        internal static string HighlightInventoriesHelp {
            get {
                return ResourceManager.GetString("HighlightInventoriesHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Tooltips.
        /// </summary>
        internal static string HighlightItemTooltipsCheckbox {
            get {
                return ResourceManager.GetString("HighlightItemTooltipsCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lists what gearsets need the item being hovered over in the item tooltip.
        /// </summary>
        internal static string HighlightItemTooltipsHelp {
            get {
                return ResourceManager.GetString("HighlightItemTooltipsHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketboard.
        /// </summary>
        internal static string HighlightMarketboardCheckbox {
            get {
                return ResourceManager.GetString("HighlightMarketboardCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlights items needed for gearsets on the marketboard.
        /// </summary>
        internal static string HighlightMarketboardHelp {
            get {
                return ResourceManager.GetString("HighlightMarketboardHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Materia Melding.
        /// </summary>
        internal static string HighlightMateriaMeldingCheckbox {
            get {
                return ResourceManager.GetString("HighlightMateriaMeldingCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlights gearpieces needing melds and the materia needed for those gearpieces in melding windows.
        /// </summary>
        internal static string HighlightMateriaMeldingHelp {
            get {
                return ResourceManager.GetString("HighlightMateriaMeldingHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need/Greed Windows.
        /// </summary>
        internal static string HighlightNeedGreedCheckbox {
            get {
                return ResourceManager.GetString("HighlightNeedGreedCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlights items needed for gearsets in Need/Greed loot windows.
        /// </summary>
        internal static string HighlightNeedGreedHelp {
            get {
                return ResourceManager.GetString("HighlightNeedGreedHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shops/Exchanges.
        /// </summary>
        internal static string HighlightShopExchangesCheckbox {
            get {
                return ResourceManager.GetString("HighlightShopExchangesCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlights items needed for gearsets in NPC shops/item exchanges.
        /// </summary>
        internal static string HighlightShopExchangesHelp {
            get {
                return ResourceManager.GetString("HighlightShopExchangesHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Fail: .
        /// </summary>
        internal static string ImportFailBase {
            get {
                return ResourceManager.GetString("ImportFailBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Error.
        /// </summary>
        internal static string ImportInternalError {
            get {
                return ResourceManager.GetString("ImportInternalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid JSON.
        /// </summary>
        internal static string ImportInvalidJson {
            get {
                return ResourceManager.GetString("ImportInvalidJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid URL.
        /// </summary>
        internal static string ImportInvalidUrl {
            get {
                return ResourceManager.GetString("ImportInvalidUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Response from URL.
        /// </summary>
        internal static string ImportInvalidWebResponse {
            get {
                return ResourceManager.GetString("ImportInvalidWebResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string ImportJsonGearsetButton {
            get {
                return ResourceManager.GetString("ImportJsonGearsetButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON.
        /// </summary>
        internal static string ImportJsonGearsetInputLabel {
            get {
                return ResourceManager.GetString("ImportJsonGearsetInputLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string ImportJsonGearsetLoading {
            get {
                return ResourceManager.GetString("ImportJsonGearsetLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import gearset from JSON.
        /// </summary>
        internal static string ImportJsonGearsetText {
            get {
                return ResourceManager.GetString("ImportJsonGearsetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Gearsets Found.
        /// </summary>
        internal static string ImportNoGearsets {
            get {
                return ResourceManager.GetString("ImportNoGearsets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No JSON to Import.
        /// </summary>
        internal static string ImportNoJson {
            get {
                return ResourceManager.GetString("ImportNoJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Response from URL.
        /// </summary>
        internal static string ImportNoWebResponse {
            get {
                return ResourceManager.GetString("ImportNoWebResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Success.
        /// </summary>
        internal static string ImportSuccess {
            get {
                return ResourceManager.GetString("ImportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum of {0} gearsets.
        /// </summary>
        internal static string ImportTooManyGearsets {
            get {
                return ResourceManager.GetString("ImportTooManyGearsets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string ImportWebGearsetButton {
            get {
                return ResourceManager.GetString("ImportWebGearsetButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        internal static string ImportWebGearsetInputLabel {
            get {
                return ResourceManager.GetString("ImportWebGearsetInputLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string ImportWebGearsetLoading {
            get {
                return ResourceManager.GetString("ImportWebGearsetLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import gearset(s) from Xivgear.app or Etro.gg.
        /// </summary>
        internal static string ImportWebGearsetText {
            get {
                return ResourceManager.GetString("ImportWebGearsetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Gearset.
        /// </summary>
        internal static string ImportWindowTitle {
            get {
                return ResourceManager.GetString("ImportWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string InventoryScanLoading {
            get {
                return ResourceManager.GetString("InventoryScanLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} gearpieces updated.
        /// </summary>
        internal static string InventoryScanUpdated {
            get {
                return ResourceManager.GetString("InventoryScanUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please log in to view/add gearsets.
        /// </summary>
        internal static string LoggedOutText {
            get {
                return ResourceManager.GetString("LoggedOutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection status locked. Inventory syncs will not uncollect.
        /// </summary>
        internal static string ManuallyCollectedTooltip {
            get {
                return ResourceManager.GetString("ManuallyCollectedTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meld.
        /// </summary>
        internal static string MeldVerb {
            get {
                return ResourceManager.GetString("MeldVerb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Materia Melds.
        /// </summary>
        internal static string MeldWindowHeader {
            get {
                return ResourceManager.GetString("MeldWindowHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Gearset.
        /// </summary>
        internal static string NewGearsetButton {
            get {
                return ResourceManager.GetString("NewGearsetButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import a new gearset.
        /// </summary>
        internal static string NewGearsetTooltip {
            get {
                return ResourceManager.GetString("NewGearsetTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum of {0} gearsets.
        /// </summary>
        internal static string NewGearsetTooltipMaxGearsets {
            get {
                return ResourceManager.GetString("NewGearsetTooltipMaxGearsets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No gearsets found. Add one or more gearsets to get started.
        /// </summary>
        internal static string NoGearsetsText {
            get {
                return ResourceManager.GetString("NoGearsetsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open config.
        /// </summary>
        internal static string OpenConfigTooltip {
            get {
                return ResourceManager.GetString("OpenConfigTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename Gearset.
        /// </summary>
        internal static string RenameGearsetTooltip {
            get {
                return ResourceManager.GetString("RenameGearsetTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strict Materia Matching.
        /// </summary>
        internal static string StrictMateriaMatchingCheckbox {
            get {
                return ResourceManager.GetString("StrictMateriaMatchingCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether auto assignment treats gearpieces with different materia as unique items
        ///
        ///When ON: Each gearpiece entry is considered unique based on its materia. So if you have multiple entries for the same gearpiece with different materia, a single inventory item can only satisfy one of them
        ///When OFF: Auto assignment ignores the materia differences and only looks at the actual gearpiece. One inventory item can satisfy multiple entries for the same gearpiece even if their materia differ
        ///
        ///Example
        ///Inventory: 1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StrictMateriaMatchingHelp {
            get {
                return ResourceManager.GetString("StrictMateriaMatchingHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync Inventory.
        /// </summary>
        internal static string SyncInventoryButton {
            get {
                return ResourceManager.GetString("SyncInventoryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update gearsets with items from your inventory.
        /// </summary>
        internal static string SyncInventoryTooltip {
            get {
                return ResourceManager.GetString("SyncInventoryTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock as Collected.
        /// </summary>
        internal static string UncollectedTooltip {
            get {
                return ResourceManager.GetString("UncollectedTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unmeld.
        /// </summary>
        internal static string UnmeldVerb {
            get {
                return ResourceManager.GetString("UnmeldVerb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Changes.
        /// </summary>
        internal static string UpdateOnItemChangeCheckbox {
            get {
                return ResourceManager.GetString("UpdateOnItemChangeCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When a change is detected in character inventories, update gearsets with items in inventories (inventory, armoury chest, equipped).
        /// </summary>
        internal static string UpdateOnItemChangeHelp {
            get {
                return ResourceManager.GetString("UpdateOnItemChangeHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login/Load.
        /// </summary>
        internal static string UpdateOnLoginLoadCheckbox {
            get {
                return ResourceManager.GetString("UpdateOnLoginLoadCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When logging in or loading {0}, update gearsets with items in inventories (inventory, armoury chest, equipped).
        /// </summary>
        internal static string UpdateOnLoginLoadHelp {
            get {
                return ResourceManager.GetString("UpdateOnLoginLoadHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin Changes.
        /// </summary>
        internal static string UpdateOnPluginChangesCheckbox {
            get {
                return ResourceManager.GetString("UpdateOnPluginChangesCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When updating {0} gearsets or settings, update gearsets with items in inventories (inventory, armoury chest, equipped).
        /// </summary>
        internal static string UpdateOnPluginChangesHelp {
            get {
                return ResourceManager.GetString("UpdateOnPluginChangesHelp", resourceCulture);
            }
        }
    }
}
